config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cleaned_videos#new"

  resources :cleaned_videos, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tik_tok_meta_api.rb
class TikTokMetaApi
  include HTTParty
  base_uri 'api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed'

  def intiailize; end

  def video_data(id)
    self.class.get('/', { query: { aweme_id: id } })
  end

  def normalized_video_url(url)
    self.class.get(url)
  end
end

app/models/video_id_from_url.rb
# frozen_string_literal: true

class VideoIdFromUrl
  # given a url in either this format 
  # https://www.tiktok.com/@tadeusofficial/video/{id}?is_from_webapp=1&sender_device=pc 
  # or https://www.tiktok.com/t/{id}/
  # return the id of the video and ensure its a valid tiktok video url
  include ActiveModel::Model

  BASE_URL_FMT = /^https?:\/\/www\.tiktok\.com\/@\w+\/video\/\d+\??[^\s]*$/.freeze
  REDIRECT_URL_FMT = /^https?:\/\/www\.tiktok\.com\/t\/\w+\/?$/.freeze
  ID_REGEX = /\/video\/(\d+)/.freeze

  attr_accessor :video_url, :video_id

  validates :video_url, presence: true
  validate :valid_url_format

  def get_id
    return nil unless valid?
  
    self.video_id = normalized_url.match(ID_REGEX)[1]
  end

  private

  def valid_url_format
    return unless video_url.present?

    # check if the url is valid url and that it matches the formats we want
    unless video_url.match(/\A#{URI::regexp}\z/) &&  (video_url.match(BASE_URL_FMT) || video_url.match(REDIRECT_URL_FMT))
      errors.add(:video_url, :invalid)
    end
  end

  def normalized_url
    # if the video url has the id in the params just return it
    return video_url unless video_url&.match(REDIRECT_URL_FMT)

    # otherwise hit the url and get the redirect url which will have the id
    response = Net::HTTP.get_response(URI(video_url))

    # overwrite the video url
    response['location']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cleaned_videos_controller.rb
class CleanedVideosController < ApplicationController
  def new
    @video = VideoIdFromUrl.new
  end

  def create
    @video = VideoIdFromUrl.new(cleaned_video_params)

    id = @video.get_id

    # TODO move all this login into the VideoIdFromUrl object and refactor
    if id.present?
      begin
        response = TikTokMetaApi.new.video_data(id)
        video_data = JSON.parse(response.body)['aweme_list'][0]['video']
        @download_urls =  video_data['play_addr']['url_list']
        @cover = video_data['dynamic_cover']['url_list'][0]
      rescue StandardError => e
        Rails.logger.debug e
        # TODO forward error to Sentry or other error tracking service
        @video.errors.add(:video_url, :parsing_error)
        render :new, status: 422
      end
    else
      render :new, status: 422
    end
  end

  private

  def cleaned_video_params
    params.require(:cleaned_video).permit(:video_url)
  end

  def parse_video_data(data)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleaned_videos_helper.rb
module CleanedVideosHelper
end

app/views/cleaned_videos/_form.html.erb
<% if @video.errors.any? %>
  <div class="text-red-500">
      <ul>
        <% @video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>
  <%= form_with model: @video, url: cleaned_videos_path, scope: :cleaned_video do |f| %>
    <div class="flex flex-col w-full">
      <%= f.text_field :video_url, placeholder: "Paste a TikTok Video URL", class: "w-full mb-8" %>
      <%= f.submit "Get Download Links", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer m-auto" %>
    </div>
  <% end %>

app/views/cleaned_videos/create.turbo_stream.erb
<turbo-stream action="update" target="form">
  <template>
    <%= render 'form' %>
  </template>
</turbo-stream>

<turbo-stream action="update" target="results">
  <template>
    <div class="mt-20 flex sm:flex-row flex-col">
      <div><%= image_tag @cover %></div>
      <div class="flex flex-col px-4 mt-4 sm:mt-0">
        <% @download_urls.each_with_index do |url, index| %>
          <%= link_to "Download MP4 Link - #{index+1}", url, target: "_blank",
            class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer mb-4" %>
        <% end %>
      </div>
    </template>
</turbo-stream>

app/views/cleaned_videos/new.html.erb
<div id="form" class="w-full px-8">
  <%= render 'form' %>
</div>


<div id="results"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Download TikTok Videos Without Watermarks | Free MP4 Downloads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Download your favorite TikTok videos without watermarks with our free MP4 downloader. No sign-up required. Get started now!">
    <meta property="og:title" content="Download TikTok Videos Without Watermarks | Free MP4 Downloads">
    <meta property="og:description" content="Download your favorite TikTok videos without watermarks with our free MP4 downloader. No sign-up required. Get started now!">
    <!-- <meta property="og:image" content="https://example.com/images/tiktok-download.png">
    <link rel="canonical" href="https://example.com/tiktok-downloader/"> -->

    <meta name="robots" content="index, follow">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex flex-col items-center py-10 max-w-[960px] m-auto">
      <h1 class="text-3xl text-center font-bold text-black-700 mb-4 px-4">TikTok Video Downloader</h1>
      <p class="mb-10">Download TikTok videos without watermarks</p>
      <%= yield %>
    </main>
  </body>
</html>